window.AI_DRIFT_MODULER = [
  { slug: '01-kartlegg-prosesser', tittel: 'Kutt tiden på rutineoppgaver med opptil 80 %', desc: 'Kartlegg det som gjentar seg i driften, og lær å bygge en fast oppskrift AI-en husker for deg.', min: 10 },
  { slug: '02-kom-i-gang', tittel: 'En AI som kjenner bedriften din', desc: 'Sett den opp én gang, og bruk den til alt etterpå. Grunnmuren som gjør resten mye raskere.', min: 6 },
  { slug: '03-automatisere-kundesvar', tittel: 'Aldri mist en kunde i innboksen', desc: 'Aldri mist en jobb fordi du ikke rakk telefonen. AI svarer i din tone, du bare godkjenner.', min: 8 },
  { slug: '04-mote-og-rapportering', tittel: 'Ferdig referat før møtet er over', desc: 'Faste maler for møtereferater og statusrapporter, så rot inn blir ryddig tekst ut på minutter.', min: 6 },
  { slug: '05-tilbud-faktura-betaling', tittel: 'Få betalt uten å jage noen', desc: 'AI skriver tilbudet og purrer de som ikke har betalt, høflig og automatisk. Pengene inn før.', min: 8 },
  { slug: '06-anmeldelser-og-omdomme', tittel: 'La kundene selge for deg', desc: 'Be om anmeldelse på akkurat rett tidspunkt, og la AI svare på alle. Bedre omdømme, null ekstra jobb.', min: 6 },
  { slug: '07-koble-appene-sammen', tittel: 'Ferdig arbeid venter hver morgen', desc: 'Sett skillene dine på en fast tidsplan med Claude Cowork, så ferdig arbeid venter på deg neste morgen.', min: 9 },
  { slug: '08-varsler-og-oppfolging', tittel: 'Ingenting glipper, uten at du må sjekke selv', desc: 'Samme Cowork-mekanikk som i forrige modul, brukt til å varsle deg automatisk når noe avviker.', min: 8 },
  { slug: '09-bli-funnet-paa-google', tittel: 'Bli lettere å finne på Google', desc: 'Hold Google-profilen levende med innlegg og svar, så flere i nærområdet finner deg.', min: 7 },
  { slug: '10-innhold-og-sosiale-medier', tittel: 'En måneds innhold på 20 minutter', desc: 'En hel måned med innlegg, nyhetsbrev og bildetekster på rundt 20 minutter.', min: 8 },
  { slug: '11-papirarbeid-og-admin', tittel: 'Få papirarbeidet unnagjort på dagtid', desc: 'La AI oppsummere, sortere og lage rutiner og sjekklister for deg.', min: 6 },
  { slug: '12-kontrakter-og-dokumenter', tittel: 'Forstå enhver kontrakt før du signerer', desc: 'La AI oversette kontrakter til vanlig norsk, finne fristene som gjemmer seg i teksten, og lage egne avtaler.', min: 7 },
  { slug: '13-innkjop-og-leverandor', tittel: 'Sammenlign leverandører på minutter', desc: 'Lim inn flere tilbud, og la AI stille dem opp i en tabell du faktisk kan sammenligne.', min: 6 },
  { slug: '14-onboarding-nyansatte', tittel: 'Onboarding uten å bruke en hel dag', desc: 'Bygg én onboardingmappe med AI, gjenbruk den for hver nyansatt som begynner.', min: 7 },
];
